name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: Cavy.xcodeproj
        scheme: Cavy
        action: test
