name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Xcode Test
      uses: sersoft-gmbh/xcodebuild-action@v1.3
      with:
        project: Cavy.xcodeproj
        scheme: Cavy
        destination: platform=iOS Simulator,name=iPhone 12
        action: test
